name: tecoacademy
description: Plataforma educativa de Teco Academy.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.4
  provider: ^6.1.1
  fl_chart: ^0.65.0
  image_picker: ^1.0.5
  cached_network_image: ^3.3.0
  intl: ^0.17.0
  url_launcher: ^6.2.2
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.0
  rxdart: ^0.27.7
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  